"use client";

import { Sparkles, Info } from "lucide-react";

interface AnalysisSummaryProps {
  summary: string;
}

export function AnalysisSummary({ summary }: AnalysisSummaryProps) {
  return (
    <div className="relative group overflow-hidden rounded-2xl border border-[#262626] bg-gradient-to-br from-[#131314] to-[#0a0a0b] p-8">
      {/* Decorative background glow */}
      <div className="absolute -top-24 -right-24 h-48 w-48 bg-[#6366f1]/5 blur-[80px] pointer-events-none" />
      
      <div className="flex items-start gap-4">
        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#6366f1]/10 border border-[#6366f1]/20">
          <Sparkles className="h-5 w-5 text-[#6366f1]" />
        </div>
        
        <div className="space-y-4">
          <div className="flex items-center gap-2">
            <h2 className="text-xl font-bold text-[#e5e2e3]">AI Repository Summary</h2>
            <div className="group/tooltip relative">
              <Info className="h-4 w-4 text-[#908fa0] cursor-help" />
              <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-48 p-2 rounded bg-[#262626] text-[10px] text-[#e5e2e3] opacity-0 group-hover/tooltip:opacity-100 transition-opacity pointer-events-none border border-[#464554] z-10">
                This summary is generated by analyzing the entire repository structure and contents.
              </div>
            </div>
          </div>
          
          <div className="prose prose-invert max-w-none">
            <p className="text-[#908fa0] text-lg leading-relaxed">
              {summary}
            </p>
          </div>
          
          <div className="flex items-center gap-4 pt-4 border-t border-[#262626]">
            <div className="flex items-center gap-2 text-xs font-medium text-[#c0c1ff]">
              <div className="h-1.5 w-1.5 rounded-full bg-[#c0c1ff]" />
              Architectural Context
            </div>
            <div className="flex items-center gap-2 text-xs font-medium text-[#4cd7f6]">
              <div className="h-1.5 w-1.5 rounded-full bg-[#4cd7f6]" />
              Beginner Friendly
            </div>
            <div className="flex items-center gap-2 text-xs font-medium text-[#ffb783]">
              <div className="h-1.5 w-1.5 rounded-full bg-[#ffb783]" />
              High Maintainability
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
